.PHONY: all clean grade-3 grade-4 grade-5

all: grade-3 grade-4 grade-5

grade-3:
	$(MAKE) -C grade-3

grade-4:
	$(MAKE) -C grade-4

grade-5:
	$(MAKE) -C grade-5

clean:
	$(MAKE) -C grade-3 clean
	$(MAKE) -C grade-4 clean
	$(MAKE) -C grade-5 clean
